/*
 * 년 / 월 / 성별 별 상품 구매 회원수 집계
    - 순서대로 오름차
    - 성별 정보가 없는 경우 제외
*/
SELECT YEAR(s.SALES_DATE) AS YEAR, 
       MONTH(s.SALES_DATE) AS MONTH,
       u.GENDER,
       COUNT(DISTINCT u.USER_ID)
FROM USER_INFO AS u INNER JOIN ONLINE_SALE AS s ON u.USER_ID = s.USER_ID
WHERE u.GENDER IS NOT NULL 
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER


# SELECT s.YEAR, s.MONTH, u.GENDER, s.USER_ID
# FROM (
#     SELECT USER_ID, GENDER
#     FROM USER_INFO) AS u 
# INNER JOIN
#      (
#     SELECT USER_ID, 
#            PRODUCT_ID, 
#            SALES_AMOUNT, 
#            # DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE
#            YEAR(SALES_DATE) AS YEAR,
#            MONTH(SALES_DATE) AS MONTH
#     FROM ONLINE_SALE
#     WHERE USER_ID IN (
#         SELECT USER_ID
#         FROM USER_INFO
#         WHERE GENDER IS NOT NULL)
#      GROUP BY YEAR, MONTH, USER_ID) AS s 
# ON u.USER_ID = s.USER_ID
# GROUP BY YEAR, MONTH, GENDER, USER_ID
# ORDER BY YEAR, MONTH, GENDER