/*
 * 우유(Milk)와 요거트(Yogurt)를 "동시에" 구입한 장바구니의 아이디
*/
SELECT m.CART_ID
FROM
(SELECT ID, CART_ID, COUNT(CART_ID)
FROM CART_PRODUCTS
WHERE NAME LIKE '%Milk%' 
GROUP BY CART_ID) as m INNER JOIN 
(SELECT ID, CART_ID, COUNT(CART_ID)
FROM CART_PRODUCTS
WHERE NAME LIKE '%Yogurt%'
GROUP BY CART_ID) as y ON m.CART_ID =  y.CART_ID
ORDER BY m.CART_ID

# HAVING COUNT(CART_ID) >= 2