/*
 - 총 주문량 : 3000보다 높은
 - 주 성분 : 과일
 - 총 주문량 DESC
*/
# SELECT o.FLAVOR AS FLAVOR
# FROM FIRST_HALF AS o LEFT JOIN ICECREAM_INFO AS i ON o.FLAVOR
# WHERE o.TOTAL_ORDER >= 3000 AND i.INGREDIENT_TYPE = 'fruit_based'
# ORDER BY o.TOTAL_ORDER DESC

SELECT o.FLAVOR AS FLAVOR
FROM FIRST_HALF AS o INNER JOIN 
    (SELECT FLAVOR 
     FROM ICECREAM_INFO
     WHERE INGREDIENT_TYPE = 'fruit_based') AS i
     ON o.FLAVOR = i.FLAVOR
WHERE o.TOTAL_ORDER >= 3000
ORDER BY o.TOTAL_ORDER DESC

