/*
 * 자동차 ID & 평균 대여 기간(소수점 두번째 자리에서 반올림)
 - 평균 대여 기간이 7일 이상
 - 대여 기간 기준 내림차, ID 내림차
*/
SELECT p.CAR_ID, ROUND(AVG(p.PERIOD),1) AS AVERAGE_DURATION
FROM (SELECT CAR_ID, (DATEDIFF(END_DATE,START_DATE)+1) AS PERIOD
     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS p
GROUP BY p.CAR_ID
HAVING AVG(p.PERIOD) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC
     