/*
 * 식품 분류별 
    가격 제일 비싼 식품 분류, 가격, 이름
        - "과자", "국", "김치", "식용유"만
        - 식품 가격 내림차
*/
SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (
    SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) 
#AND CATEGORY IN ("과자", "국", "김치", "식용유")
ORDER BY PRICE DESC

# SELECT CATEGORY, MAX(PRICE)
# FROM FOOD_PRODUCT
# WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
# GROUP BY CATEGORY
# ORDER BY PRICE DESC

# SELECT *
# FROM FOOD_PRODUCT
# ORDER BY CATEGORY, PRICE DESC
    
# GROUP BY CATEGORY

# WHERE PRODUCT_NAME LIKE '%과자%' OR
#       PRODUCT_NAME LIKE '%국%' OR
#       PRODUCT_NAME LIKE '%김치%' OR
#       PRODUCT_NAME LIKE '%식용유%'