# -- 코드를 입력하세요
# SELECT CATEGORY, COUNT(BOOK_ID)
# WHERE BOOK_ID IN (SELECT CATEGORY, COUNT(BOOK_ID) 
#     FROM BOOK_SALES
#     WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01' 
#     GROUP BY CATEGORY)
#     AND 
# GROUP BY CATEGORY
# ORDER BY CATEGORY ASC

# 경제 책 ID
# (SELECT BOOK_ID, CATEGORY
# FROM BOOK
# WHERE CATEGORY = '경제')
# (SELECT BOOK_ID, CATEGORY
# FROM BOOK
# WHERE CATEGORY = '인문')

# SELECT SUM(SALES)
# SELECT CASE WITH BOOK_ID IN()
# FROM BOOK_SALES
# WHERE BOOK_ID IN

# SELECT CATEGORY, COUNT(BOOK_ID) 
#     FROM BOOK_SALES as bs  LEFT JOIN BOOK as b ON bs.BOOK_ID = b.BOOK_ID
#     WHERE DATE_FORMAT(bs.SALES_DATE, '%Y-%m') = '2022-01' 
#     GROUP BY b.CATEGORY

SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK as b INNER JOIN BOOK_SALES as bs ON b.BOOK_ID = bs.BOOK_ID
WHERE DATE_FORMAT(bs.SALES_DATE, '%Y-%m') = '2022-01' 
GROUP BY CATEGORY
ORDER BY CATEGORY
