/*
 * 상품 코드 별 매출액(판매가 * 판매량) 의 합계
 - 매출액 내림차, 코드 오름차
*/
SELECT p.PRODUCT_CODE, SUM(o.SALES_AMOUNT * p.PRICE) AS SALES
FROM PRODUCT AS p RIGHT JOIN OFFLINE_SALE AS o ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY o.PRODUCT_ID
ORDER BY SALES DESC, p.PRODUCT_CODE ASC

