/*
 * 회원 ID, 상품 ID
 - 동일 회원 동일 상품 재구매 데이터
 - 회원 ID 오름차, 상품 ID 내림차
*/
# SELECT USER_ID,  PRODUCT_ID
# FROM ONLINE_SALE
# WHERE 
# ORDER BY USER_ID ASC, PRODUCT_ID DESC

/*
 * 2회 이상 구매한 유저 
 */
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY PRODUCT_ID, USER_ID
HAVING COUNT(USER_ID) >= 2
ORDER BY USER_ID ASC, PRODUCT_ID DESC

# SELECT USER_ID, PRODUCT_ID
# FROM ONLINE_SALE
# WHERE USER_ID = 2