/*
 * 각 성분 타입, 타입 별 총 주문량
 
 - 총 주문량 오름차
*/
SELECT i.INGREDIENT_TYPE, SUM(f.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS f LEFT JOIN ICECREAM_INFO AS i ON f.FLAVOR = i.FLAVOR
GROUP BY i.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC