/*
 ID, 저자명, 출반일
 - 카테고리 '경제'
*/
SELECT b.BOOK_ID, a.AUTHOR_NAME, SUBSTR(b.PUBLISHED_DATE,1,10) as PUBLISHED_DATE
FROM BOOK as b INNER JOIN AUTHOR as a ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE b.CATEGORY = '경제'
ORDER BY b.PUBLISHED_DATE ASC ;