/*
 
*/
SELECT t.CAR_TYPE, COUNT(t.CAR_TYPE) as CARS
FROM (SELECT CAR_TYPE
        FROM CAR_RENTAL_COMPANY_CAR
        WHERE OPTIONS LIKE '%통풍시트%' OR OPTIONS LIKE '%열선시트%' OR OPTIONS LIKE '%가죽시트%')as t
GROUP BY t.CAR_TYPE
ORDER BY t.CAR_TYPE